### ISSUE TITLE
`flask run` produces `ValueError: max() arg is an empty sequence`

### ISSUE THREAD

**Issue by MaxGhenis** [PolicyEngine/policyengine-uk-old#2]
I'm up to date on `openfisca-uk`, might I need to install or update something else?
```
(base) mghenis@penguin:~/nikhilwoodruff/openfisca-uk-ui$ export FLASK_APP=server/server.py
(base) mghenis@penguin:~/nikhilwoodruff/openfisca-uk-ui$ flask run
 * Serving Flask app "server/server.py"
 * Environment: production
   WARNING: This is a development server. Do not use it in a production deployment.
   Use a production WSGI server instead.
 * Debug mode: off
Traceback (most recent call last):
  File "/home/mghenis/anaconda3/bin/flask", line 10, in <module>
    sys.exit(main())
  File "/home/mghenis/anaconda3/lib/python3.7/site-packages/flask/cli.py", line 967, in main
    cli.main(args=sys.argv[1:], prog_name="python -m flask" if as_module else None)
  File "/home/mghenis/anaconda3/lib/python3.7/site-packages/flask/cli.py", line 586, in main
    return super(FlaskGroup, self).main(*args, **kwargs)
  File "/home/mghenis/anaconda3/lib/python3.7/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/home/mghenis/anaconda3/lib/python3.7/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/mghenis/anaconda3/lib/python3.7/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/mghenis/anaconda3/lib/python3.7/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/home/mghenis/anaconda3/lib/python3.7/site-packages/click/decorators.py", line 73, in new_func
    return ctx.invoke(f, obj, *args, **kwargs)
  File "/home/mghenis/anaconda3/lib/python3.7/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/home/mghenis/anaconda3/lib/python3.7/site-packages/flask/cli.py", line 848, in run_command
    app = DispatchingApp(info.load_app, use_eager_loading=eager_loading)
  File "/home/mghenis/anaconda3/lib/python3.7/site-packages/flask/cli.py", line 305, in __init__
    self._load_unlocked()
  File "/home/mghenis/anaconda3/lib/python3.7/site-packages/flask/cli.py", line 330, in _load_unlocked
    self._app = rv = self.loader()
  File "/home/mghenis/anaconda3/lib/python3.7/site-packages/flask/cli.py", line 388, in load_app
    app = locate_app(self, import_name, name)
  File "/home/mghenis/anaconda3/lib/python3.7/site-packages/flask/cli.py", line 240, in locate_app
    __import__(module_name)
  File "/home/mghenis/nikhilwoodruff/openfisca-uk-ui/server/server.py", line 26, in <module>
    baseline = openfisca_uk.Microsimulation()
  File "/home/mghenis/PSLmodels/openfisca-uk/openfisca_uk/tools/simulation.py", line 219, in __init__
    self.year = max(dataset().years)
ValueError: max() arg is an empty sequence
```

**Comment by nikhilwoodruff** [comment]
This error is caused by not having installed the microdata h5 file - I'll add to the instructions to clarify.

**Comment by nikhilwoodruff** [comment]
Think this is fixed, but feel free to reopen if it recurs for anyone.
